name = "hyde"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/Keats/gutenberg-hyde"
min_version = "0.2"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""

[author]
name = "Vincent Prouillet"
homepage = "https://vincent.is"

[original]
author =  "mdo"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"
